### ISSUE TITLE
initial private message does not include receipients

### ISSUE THREAD

**Issue by evbogue** [dominictarr/patchless#7]
@dominictarr and I discovered this when I tried to send him and @mixmix a private message from Patchless. 

**What happens?** A private message is written and published by scuttlebot, but it must not be including the recipients, because no one receives the message (including the sender).

**To reproduce** try using the patchless compose button to send a private message to someone. You will see that you did not receive the message, and the other person will confirm that they did not receive the message.

**Comment by dominictarr** [comment]
looked into this... yeah, the old way, was that mentioned recipients + yourself is added to the message by something supplying `patchcompose.post`

https://github.com/dominictarr/patchcompose/blob/master/index.js#L57

I think I didn't get around to implementing this because I was thinking of making an input for explicit recipients a la patchwork@2 rather than the mentions shortcut patchbay used. Or at least, showing the recipient's avatars. The thing that blocked me is it would need to respond to the text area changing but `compose.context` can't do that. `compose.insert` can... this is a similar problem to where to put the actions and meta options on messages... maybe it should be more flexible (like just return one thing... then arrange them? maybe by looking at css classes?)

**Comment by evbogue** [comment]
Private messages include recps now, closing.
